# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOYeC9o2C3isEdYrMiqWlgctb8Llkf0i
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

#100000 samples
simlen=100000

# probability of event
prob=2/3

#generating sample data
data_bern = bernoulli.rvs(size=simlen,p=prob)
#number of events whose probabilty is 2/3
err_ind = np.nonzero(data_bern == 1)
#calculating probability
err_n = np.size(err_ind)/simlen

#simulation vs theory
print(err_n,prob)
print(data_bern)