# -*- coding: utf-8 -*-
"""Assignment8.1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15VWfvatv6kW4mlaaGjhdDzJftwkKY2gT
"""

import numpy as np
i=0
#mean of standard normal distribution
mu=0
#standard deviation of standard normal distribution
sigma=1
X=[None]*100000
while i<100000:
  #generating randaom sample of size 5
  sample=np.random.normal(mu,sigma,5)
  #mean of the sample
  sam_mean=np.mean(sample)
  #standard deviation of sample
  T=5*((np.std(sample))**2)
  X[i]=((sam_mean)*(T))**2
  i+=1
j=0
s=0
while j<100000:
  s=s+X[j] 
  j+=1
#expectation value
e=s/100000 
print(e)