# -*- coding: utf-8 -*-
"""Assignmnet7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LKOtp4H_VGZ-yIflft9HJlkPqftoEGej
"""

import matplotlib.pyplot as plt
import numpy as np
  
def p_sign(x):
    if (x==1):
        return 1/2 
    elif (x==-1):
        return 1/2     
    else:
       return 0

X = np.linspace(-3,3,1000000)

Y = [p_sign(x) for x in X]
plt.xlabel('Y=sign(X)')
plt.ylabel('$pdf $')
plt.plot(X,Y)
plt.grid()
plt.savefig('Assignment7.png' , dpi=100)
plt.show()