# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8EDZd7yzn2BX4H1rlqg5-69n9Sml29M
"""

import numpy as np
import random
import matplotlib.pyplot as plt
from scipy.stats import bernoulli

# given probabilities
p_e = 1/2
p_f = 1/3
p_g = 1/4
# simulation length 
simlen = 100000
#generating data for event E
data_bern_p_e = bernoulli.rvs(size=simlen,p=p_e)
#generatind data for event F
data_bern_p_f = bernoulli.rvs(size=simlen,p=p_f)
#generatind data for event G
data_bern_p_g = bernoulli.rvs(size=simlen,p=p_g)
#adding three arrays
out = np.array([data_bern_p_e,data_bern_p_f,data_bern_p_g]) # '1' represents the computer is declared as faulty
final=np.add(0,out.sum(axis=0))

#calculating number of occurences all te three events
count3 = np.count_nonzero(final == 3)
#calculating number of occurences of at;east two events
count2 = np.count_nonzero(final == 2)
#calculating  simulated probability of occuring atleast two events
p_sim = (count2+count3)/simlen

print(final)
print(count2)
print(count3)
print(p_sim)