# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-iKmrJz50eOSQg32Bgo8KHRw1BWyUBWE
"""

from random import choices
from collections import Counter

#theoritical probability 
th_pr_jim = 0.88
th_pr_suj = 0.96

#simulation
x = [0,1,2] #random variable 0:good shirt  1:minor defect  2:major defect
pr = [0.88,0.08,0.04]
#1000 simulations
simlen = 1000

#generating data
sample = choices(x,pr,k=simlen)

#counting number of good shirts,minor defect shirts,major defect shirts
_count = Counter(sample)

num_good = _count[0]
num_minor = _count[1]
num_major = _count[2]

#calculating probability of drawing each type of shirt 
pr_good = num_good/simlen
pr_minor = num_minor/simlen
pr_major = num_major/simlen

#calculating probability of acceptance of shirt by jimmy and sujatha respectively
pr_jimmy = pr_good
pr_sujatha = pr_good+pr_minor







#plotting probability of each random variable
import matplotlib.pyplot as plt 
  
# x-coordinates of left sides of bars  
left = [0 , 1 , 2 ] 
  
# heights of bars 
height = [88 , 8 , 4] 
  
# labels for bars 
tick_label = ['zero' , 'one' , 'two'] 
  
# plotting a bar chart 
plt.bar(left, height, tick_label = tick_label, 
        width = 0.8, color = ['red', 'green']) 
  
# naming the x-axis 
plt.xlabel('value of random variable X') 
# naming the y-axis 
plt.ylabel('pr(X)*100') 
# plot title 
plt.title('plot of theoretical probability') 
  
# function to show the plot 
plt.savefig('plot.png' , dpi=300)
plt.show() 









print(sample)
print(_count)
print("theoretical probability :",th_pr_jim,th_pr_suj)
print("simulated probability : ",pr_jimmy , pr_sujatha)

_