# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12B_0hqEV3CSlqA4fDhrI8Txsm2A4mSiF
"""

import numpy as np
from numpy import linalg as LA
#symmetric matrix M
M=np.array([[0.8,-0.2,-0.2,-0.2,-0.2],[ -0.2,0.8,-0.2,-0.2,-0.2], [-0.2,-0.2,0.8,-0.2,-0.2], [-0.2,-0.2,-0.2,0.8,-0.2], [-0.2,-0.2,-0.2,-0.2,0.8]])
#calculating eigen values and normalised eigen vectors
w,vec=LA.eigh(M)

print(w)
print(np.dot(vec,vec.T))#verify v is orthogonal
# calculating  equation 8.4.25
ut=np.array([[1,1,1,1,1]])
v=np.array([[0],[1],[1],[1],[1]])
f=np.dot(ut,vec)
np.dot(f,v)